/*
 * Keypad_Config.h
 *
 *  Created on: Feb 16, 2019
 *      Author: islash8
 */


#ifndef KEYPAD_CONFIG_H_
#define KEYPAD_CONFIG_H_

#define KEYPAD_u8_TOTAL_NUM (u8)1

#define KEYPAD_u8_ROW_SIZE		4
#define KEYPAD_u8_COLUMN_SIZE	4

#define KEYPAD_u8_ROW_ONE		DIO_PIN24
#define KEYPAD_u8_ROW_TWO		DIO_PIN25
#define KEYPAD_u8_ROW_THREE		DIO_PIN26
#define KEYPAD_u8_ROW_FOUR		DIO_PIN27

#define KEYPAD_u8_COLUMN_ONE	DIO_PIN28
#define KEYPAD_u8_COLUMN_TWO	DIO_PIN29
#define KEYPAD_u8_COLUMN_THREE	DIO_PIN30
#define KEYPAD_u8_COLUMN_FOUR	DIO_PIN31

#define KPD_u8_TYPE 			KEYPAD_ACTIVE_LOW


u8 KPD_Au8RowsPins[KEYPAD_u8_ROW_SIZE]
= {KEYPAD_u8_ROW_ONE, KEYPAD_u8_ROW_TWO, KEYPAD_u8_ROW_THREE, KEYPAD_u8_ROW_FOUR};
u8 KPD_Au8ColumnsPins[KEYPAD_u8_ROW_SIZE]
= {KEYPAD_u8_COLUMN_ONE, KEYPAD_u8_COLUMN_TWO, KEYPAD_u8_COLUMN_THREE, KEYPAD_u8_COLUMN_FOUR};

#endif /* KEYPAD_CONFIG_H_ */
